package ngl.relay.app;
import android.content.*; import java.util.*; import ngl.relay.core.*;
public final class NodeRegistry {
 public static final String PREFS="ngl_relay_prefs"; public static final int DEFAULT_TIMEOUT=90000,DEFAULT_CONTEXT_BUDGET=24000;
 public static final class Slot {public final String id,provider,defaultModel,defaultBase,label; Slot(String i,String p,String m,String b,String l){id=i;provider=p;defaultModel=m;defaultBase=b;label=l;}}
 public static final Slot[] KNOWN_NODES={new Slot("openai","openai","gpt-4o-mini","https://api.openai.com/v1","ChatGPT"),new Slot("gemini","google-gemini","gemini-2.0-flash","https://generativelanguage.googleapis.com/v1beta","Gemini"),new Slot("grok","xai-grok","grok-3-latest","https://api.x.ai/v1","Grok"),new Slot("claude","anthropic-claude","claude-3-5-haiku-20241022","https://api.anthropic.com/v1","Claude")};
 static SharedPreferences prefs(Context c){return c.getSharedPreferences(PREFS,Context.MODE_PRIVATE);} static Slot slot(String id){for(Slot s:KNOWN_NODES)if(s.id.equals(id))return s;throw new IllegalArgumentException(id);}
 public static String apiKey(Context c,String id){return prefs(c).getString("node."+id+".key","");} public static boolean enabled(Context c,String id){return prefs(c).getBoolean("node."+id+".enabled",false);} public static String model(Context c,String id){String v=prefs(c).getString("node."+id+".model","");return v==null||v.trim().isEmpty()?slot(id).defaultModel:v;} public static String baseUrl(Context c,String id){String v=prefs(c).getString("node."+id+".base","");return v==null||v.trim().isEmpty()?slot(id).defaultBase:v;} public static int timeoutMillis(Context c){return prefs(c).getInt("timeoutMillis",DEFAULT_TIMEOUT);} public static int contextBudgetChars(Context c){return prefs(c).getInt("contextBudgetChars",DEFAULT_CONTEXT_BUDGET);} 
 public static void setApiKey(Context c,String id,String v){prefs(c).edit().putString("node."+id+".key",v).apply();} public static void setEnabled(Context c,String id,boolean v){prefs(c).edit().putBoolean("node."+id+".enabled",v).apply();} public static void setModel(Context c,String id,String v){prefs(c).edit().putString("node."+id+".model",v).apply();} public static void setBaseUrl(Context c,String id,String v){prefs(c).edit().putString("node."+id+".base",v).apply();} public static void setTimeoutMillis(Context c,int v){prefs(c).edit().putInt("timeoutMillis",Math.max(5000,v)).apply();} public static void setContextBudgetChars(Context c,int v){prefs(c).edit().putInt("contextBudgetChars",Math.max(4000,v)).apply();}
 public static List<Node> activeNodes(Context c){List<Node> out=new ArrayList<>();for(Slot s:KNOWN_NODES){String k=apiKey(c,s.id);if(!enabled(c,s.id)||k==null||k.trim().isEmpty())continue;switch(s.id){case"openai":out.add(new OpenAiNode(s.id,k,baseUrl(c,s.id),model(c,s.id)));break;case"gemini":out.add(new GeminiNode(s.id,k,baseUrl(c,s.id),model(c,s.id)));break;case"grok":out.add(new GrokNode(s.id,k,baseUrl(c,s.id),model(c,s.id)));break;case"claude":out.add(new ClaudeNode(s.id,k,baseUrl(c,s.id),model(c,s.id),null));}}return out;}
}
