package ngl.relay.core;
import java.util.*;
public final class Artifact {
  public final String id,caseId,nodeId,provider,model,status,error,content,contentType,hash,createdAt; public final Type type; public final int stage; public final List<String> parents;
  public enum Type {HUMAN_INPUT("human_input"),NORMALIZED_INPUT("normalized_input"),NODE_REQUEST("node_request"),NODE_RESPONSE("node_response"),CRITIQUE("critique"),COMPARISON("comparison"),DELIBERATION("deliberation"),SYNTHESIS("synthesis"),HUMAN_ANNOTATION("human_annotation"),HUMAN_DECISION("human_decision"),ERROR("error"),SYSTEM_EVENT("system_event"),CONTEXT_COMPACT("context_compact"); public final String wire;Type(String w){wire=w;}public static Type fromWire(String w){for(Type t:values())if(t.wire.equals(w))return t;throw new IllegalArgumentException("unknown artifact type: "+w);}}
  private Artifact(Builder b){stage=b.stage;id=b.id!=null?b.id:UUID.randomUUID().toString();caseId=(String)req(b.caseId,"caseId");type=(Type)req(b.type,"type");nodeId=b.nodeId;provider=(String)req(b.provider,"provider");model=b.model;status=(String)req(b.status,"status");error=b.error;content=b.content==null?"":b.content;contentType=b.contentType==null?"text/plain":b.contentType;hash=b.hash!=null?b.hash:CoreJson.sha256Hex(content);createdAt=b.createdAt!=null?b.createdAt:Iso8601.now();parents=Collections.unmodifiableList(new ArrayList<>(b.parents==null?Collections.<String>emptyList():b.parents));}
  private static Object req(Object o,String n){if(o==null)throw new IllegalArgumentException("Artifact requires "+n);return o;} public static Builder builder(String caseId,Type t,int stage){return new Builder(caseId,t,stage);}
  public static final class Builder {String caseId,nodeId,provider="system",model,status="recorded",error,content="",contentType="text/plain",hash,createdAt,id;Type type;int stage;List<String>parents=new ArrayList<>();Builder(String c,Type t,int s){caseId=c;type=t;stage=s;}public Builder id(String v){id=v;return this;}public Builder nodeId(String v){nodeId=v;return this;}public Builder provider(String v){provider=v;return this;}public Builder model(String v){model=v;return this;}public Builder status(String v){status=v;return this;}public Builder error(String v){error=v;return this;}public Builder content(String v){content=v;return this;}public Builder contentType(String v){contentType=v;return this;}public Builder hash(String v){hash=v;return this;}public Builder createdAt(String v){createdAt=v;return this;}public Builder parent(String v){parents.add(v);return this;}public Builder parents(List<String>v){parents.addAll(v);return this;}public Artifact build(){return new Artifact(this);}}
  public String toJson(){StringBuilder b=new StringBuilder(content.length()*2+256);b.append('{');CoreJson.obj(b,"id",id);b.append(',');CoreJson.obj(b,"case_id",caseId);b.append(',');CoreJson.obj(b,"type",type.wire);b.append(",\"stage\":").append(stage).append(',');CoreJson.obj(b,"node_id",nodeId);b.append(',');CoreJson.obj(b,"provider",provider);b.append(',');CoreJson.obj(b,"model",model);b.append(',');CoreJson.obj(b,"status",status);b.append(',');CoreJson.obj(b,"error",error);b.append(',');CoreJson.obj(b,"content_type",contentType);b.append(',');CoreJson.obj(b,"hash",hash);b.append(',');CoreJson.obj(b,"created_at",createdAt);b.append(",\"parents\":[");for(int i=0;i<parents.size();i++){if(i>0)b.append(',');CoreJson.str(b,parents.get(i));}b.append("],");CoreJson.obj(b,"content",content);return b.append('}').toString();}
  public static Artifact fromJson(String json){CoreJson.JObject o=CoreJson.parseObject(json);Builder b=builder(o.get("case_id"),Type.fromWire(o.get("type")),(int)o.getNum("stage",0)).id(o.get("id")).nodeId(o.get("node_id")).provider(o.get("provider","system")).model(o.get("model")).status(o.get("status","recorded")).error(o.get("error")).contentType(o.get("content_type","text/plain")).hash(o.get("hash")).createdAt(o.get("created_at")).content(o.get("content", ""));List<String> p=o.getList("parents");if(p!=null)b.parents(p);return b.build();}
  public boolean equals(Object x){return x instanceof Artifact&&id.equals(((Artifact)x).id);}public int hashCode(){return id.hashCode();}public String toString(){return type.wire+"#"+id.substring(0,8)+" s"+stage+(provider==null?"":" "+provider);}
}
