package ngl.relay.core;
import java.io.*; import java.nio.charset.StandardCharsets; import java.util.*; import java.util.concurrent.ThreadLocalRandom;
public final class CaseStore {
  public static final class CaseMeta {public final String caseId,title,createdAt,updatedAt,originalInputArtifactId,humanDecision;public final int methodologyStage;public CaseMeta(String c,String t,String ca,String ua,String oi,int s,String hd){caseId=c;title=t;createdAt=ca;updatedAt=ua;originalInputArtifactId=oi;methodologyStage=s;humanDecision=hd;}public String toJson(){StringBuilder b=new StringBuilder(256).append('{');CoreJson.obj(b,"case_id",caseId);b.append(',');CoreJson.obj(b,"title",title);b.append(',');CoreJson.obj(b,"created_at",createdAt);b.append(',');CoreJson.obj(b,"updated_at",updatedAt);b.append(',');CoreJson.obj(b,"original_input_artifact_id",originalInputArtifactId);b.append(",\"methodology_stage\":").append(methodologyStage).append(',');CoreJson.obj(b,"human_decision",humanDecision);return b.append('}').toString();}public static CaseMeta fromJson(String s){CoreJson.JObject o=CoreJson.parseObject(s);return new CaseMeta(o.get("case_id"),o.get("title"),o.get("created_at"),o.get("updated_at"),o.get("original_input_artifact_id"),(int)o.getNum("methodology_stage",0),o.get("human_decision"));}}
  private final File root; public CaseStore(File appRoot){root=new File(appRoot,"cases");mkdirs(root);} private File caseDir(String id){return new File(root,id);}
  public CaseMeta createCase(String title,String input){String id="case-"+Long.toHexString(System.currentTimeMillis())+"-"+Integer.toHexString(ThreadLocalRandom.current().nextInt());File d=caseDir(id);mkdirs(d);mkdirs(new File(d,"artifacts"));Artifact a=Artifact.builder(id,Artifact.Type.HUMAN_INPUT,0).provider("human").status("recorded").content(input).build();appendArtifact(d,a);String t=title==null||title.trim().isEmpty()?defaultTitle(input):title.trim();CaseMeta m=new CaseMeta(id,t,a.createdAt,a.createdAt,a.id,0,null);writeMeta(d,m);return m;}
  private static String defaultTitle(String s){String x=s==null?"":s.replaceAll("\\s+"," ").trim();if(x.isEmpty())return "Untitled case";return x.length()>60?x.substring(0,57)+"...":x;}
  public Artifact appendArtifact(String caseId,Artifact a){return appendArtifact(caseDir(caseId),a);} private Artifact appendArtifact(File d,Artifact a){if(!d.isDirectory())throw new IllegalArgumentException("case directory missing: "+d);if(!a.caseId.equals(d.getName()))throw new IllegalArgumentException("artifact case mismatch");File ad=new File(d,"artifacts");mkdirs(ad);File dest=new File(ad,a.id+".json");if(dest.exists())throw new IllegalStateException("IMMUTABILITY VIOLATION: artifact already exists: "+a.id);if(!CoreJson.sha256Hex(a.content).equals(a.hash))throw new IllegalArgumentException("hash mismatch for artifact "+a.id);for(String p:a.parents)if(!new File(ad,p+".json").exists())throw new IllegalArgumentException("unknown parent artifact "+p+" (append order violated — provenance must be created first)");File tmp=new File(ad,a.id+".json.tmp");writeFile(tmp,a.toJson());moveAtomicish(tmp,dest);try(FileOutputStream out=new FileOutputStream(new File(d,"record.jsonl"),true)){String e="{\"event\":\"appended\",\"artifact_id\":\""+a.id+"\",\"type\":\""+a.type.wire+"\",\"stage\":"+a.stage+",\"ts\":\""+Iso8601.now()+"\"}\n";out.write(e.getBytes(StandardCharsets.UTF_8));}catch(IOException e){throw new IllegalStateException("cannot append record log",e);}return a;}
  public Artifact getArtifact(String caseId,String artifactId){File f=new File(new File(caseDir(caseId),"artifacts"),artifactId+".json");return f.exists()?Artifact.fromJson(readFile(f)):null;} public CaseMeta getMeta(String caseId){File f=new File(caseDir(caseId),"case.json");return f.exists()?CaseMeta.fromJson(readFile(f)):null;}
  public void updateMeta(CaseMeta m){File d=caseDir(m.caseId);if(!d.isDirectory())throw new IllegalArgumentException("case directory missing: "+d);writeMeta(d,m);}
  public List<CaseMeta> listCases(){List<CaseMeta> out=new ArrayList<>();File[] fs=root.listFiles();if(fs==null)return out;for(File d:fs)if(d.isDirectory())try{CaseMeta m=getMeta(d.getName());if(m!=null)out.add(m);}catch(Exception ignored){}out.sort((a,b)->b.updatedAt.compareTo(a.updatedAt));return out;}
  public List<Artifact> listArtifacts(String caseId){File ad=new File(caseDir(caseId),"artifacts");List<Artifact> out=new ArrayList<>();File[] fs=ad.listFiles((dir,n)->n.endsWith(".json")&&!n.endsWith(".tmp"));if(fs==null)return out;for(File f:fs)try{out.add(Artifact.fromJson(readFile(f)));}catch(Exception ignored){}out.sort(Comparator.comparing((Artifact a)->a.createdAt).thenComparing(a->a.id));return out;}
  public List<Artifact> byStage(String c,int s){List<Artifact>o=new ArrayList<>();for(Artifact a:listArtifacts(c))if(a.stage==s)o.add(a);return o;}public List<Artifact> byType(String c,Artifact.Type t){List<Artifact>o=new ArrayList<>();for(Artifact a:listArtifacts(c))if(a.type==t)o.add(a);return o;}public List<Artifact> children(String c,String p){List<Artifact>o=new ArrayList<>();for(Artifact a:listArtifacts(c))if(a.parents.contains(p))o.add(a);return o;}public int maxStage(String c){int m=0;for(Artifact a:listArtifacts(c))m=Math.max(m,a.stage);return m;}
  public List<String> recordLog(String c){return readLines(new File(caseDir(c),"record.jsonl"));} public List<String> audit(String c){List<String> issues=new ArrayList<>();Map<String,Artifact> all=new LinkedHashMap<>();for(Artifact a:listArtifacts(c))all.put(a.id,a);for(Artifact a:all.values()){if(!CoreJson.sha256Hex(a.content).equals(a.hash))issues.add("hash mismatch: "+a.id);for(String p:a.parents)if(!all.containsKey(p))issues.add("missing parent "+p+" for "+a.id);}return issues;}
  private void writeMeta(File d,CaseMeta m){File tmp=new File(d,"case.json.tmp"),dst=new File(d,"case.json");writeFile(tmp,m.toJson());moveAtomicish(tmp,dst);}private static void moveAtomicish(File a,File b){if(!a.renameTo(b)){copyFile(a,b);delete(a);}}
  private static void mkdirs(File f){if(!f.isDirectory()&&!f.mkdirs())throw new IllegalStateException("cannot create directory "+f);}private static void writeFile(File f,String s){try(FileOutputStream o=new FileOutputStream(f)){o.write(s.getBytes(StandardCharsets.UTF_8));o.getFD().sync();}catch(IOException e){throw new IllegalStateException("cannot write "+f,e);}}private static String readFile(File f){try{byte[] b=new byte[(int)f.length()];try(FileInputStream in=new FileInputStream(f)){int p=0,n;while(p<b.length&&(n=in.read(b,p,b.length-p))>0)p+=n;}return new String(b,StandardCharsets.UTF_8);}catch(IOException e){throw new IllegalStateException("cannot read "+f,e);}}private static List<String> readLines(File f){List<String>o=new ArrayList<>();if(!f.exists())return o;try(BufferedReader r=new BufferedReader(new InputStreamReader(new FileInputStream(f),StandardCharsets.UTF_8))){String x;while((x=r.readLine())!=null)if(!x.trim().isEmpty())o.add(x);}catch(IOException e){throw new IllegalStateException("cannot read "+f,e);}return o;}private static void copyFile(File a,File b){try(FileInputStream in=new FileInputStream(a);FileOutputStream out=new FileOutputStream(b)){byte[]buf=new byte[4096];int n;while((n=in.read(buf))!=-1)out.write(buf,0,n);}catch(IOException e){throw new IllegalStateException("cannot copy "+a+" -> "+b,e);}}private static void delete(File f){if(f.exists()&&!f.delete())throw new IllegalStateException("cannot delete "+f);}
}
