package ngl.relay.core;
import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.util.*;
public final class CoreJson {
  private CoreJson(){}
  public static String sha256Hex(String s){try{byte[] d=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder b=new StringBuilder(64);for(byte x:d){b.append(Character.forDigit((x>>>4)&15,16));b.append(Character.forDigit(x&15,16));}return b.toString();}catch(Exception e){throw new IllegalStateException(e);}}
  public static void obj(StringBuilder b,String k,String v){b.append('"').append(k).append("\":");str(b,v);}
  public static void str(StringBuilder b,String s){if(s==null){b.append("null");return;}b.append('"');for(int i=0;i<s.length();i++){char c=s.charAt(i);switch(c){case '\\':b.append("\\\\");break;case '"':b.append("\\\"");break;case '\r':b.append("\\r");break;case '\f':b.append("\\f");break;case '\n':b.append("\\n");break;case '\t':b.append("\\t");break;case '\b':b.append("\\b");break;default:if(c<32)b.append(String.format("\\u%04x",(int)c));else b.append(c);}}b.append('"');}
  public static JObject parseObject(String s){if(s==null)throw new IllegalArgumentException("null json");Object o=new Parser(s).parse();if(!(o instanceof JObject))throw new IllegalArgumentException("not a JSON object");return (JObject)o;}
  @SuppressWarnings("unchecked") public static List<Object> parseArray(String s){Object o=new Parser(s).parse();if(!(o instanceof List))throw new IllegalArgumentException("not a JSON array");return (List<Object>)o;}
  public static final class JObject extends LinkedHashMap<String,Object>{
    public String get(String k){Object v=super.get(k);return v==null?null:String.valueOf(v);} public String get(String k,String d){String v=get(k);return v==null?d:v;}
    public double getNum(String k,double d){Object v=super.get(k);return v instanceof Number?((Number)v).doubleValue():d;}
    @SuppressWarnings("unchecked") public List<String> getList(String k){Object v=super.get(k);if(!(v instanceof List))return null;List<String> out=new ArrayList<>();for(Object x:(List<Object>)v)out.add(x==null?null:String.valueOf(x));return out;}
    public JObject getObject(String k){Object v=super.get(k);return v instanceof JObject?(JObject)v:null;}
    @SuppressWarnings("unchecked") public List<Object> getAnyList(String k){Object v=super.get(k);return v instanceof List?(List<Object>)v:null;}
  }
  public static final class Parser {private final String s;private int p; Parser(String s){this.s=s;} Object parse(){ws();Object v=value();ws();if(p!=s.length())throw err("trailing json");return v;} private Object value(){ws();if(p>=s.length())throw err("unexpected end");char c=s.charAt(p);if(c=='{')return object();if(c=='[')return array();if(c=='"')return string();if(c=='t'){lit("true");return Boolean.TRUE;}if(c=='f'){lit("false");return Boolean.FALSE;}if(c=='n'){lit("null");return null;}return number();} private JObject object(){JObject o=new JObject();p++;ws();if(peek('}')){p++;return o;}while(true){ws();String k=string();ws();need(':');Object v=value();o.put(k,v);ws();if(peek('}')){p++;return o;}need(',');}} private List<Object> array(){List<Object>a=new ArrayList<>();p++;ws();if(peek(']')){p++;return a;}while(true){a.add(value());ws();if(peek(']')){p++;return a;}need(',');}} private String string(){need('"');StringBuilder b=new StringBuilder();while(p<s.length()){char c=s.charAt(p++);if(c=='"')return b.toString();if(c!='\\'){b.append(c);continue;}if(p>=s.length())throw err("bad escape");c=s.charAt(p++);switch(c){case'"':b.append('"');break;case'\\':b.append('\\');break;case'/':b.append('/');break;case'b':b.append('\b');break;case'f':b.append('\f');break;case'n':b.append('\n');break;case'r':b.append('\r');break;case't':b.append('\t');break;case'u':if(p+4>s.length())throw err("bad unicode");b.append((char)Integer.parseInt(s.substring(p,p+4),16));p+=4;break;default:throw err("bad escape");}}throw err("unterminated string");} private Number number(){int st=p;if(peek('-'))p++;while(p<s.length()&&Character.isDigit(s.charAt(p)))p++;if(peek('.')){p++;while(p<s.length()&&Character.isDigit(s.charAt(p)))p++;}if(p<s.length()&&(s.charAt(p)=='e'||s.charAt(p)=='E')){p++;if(peek('+')||peek('-'))p++;while(p<s.length()&&Character.isDigit(s.charAt(p)))p++;}String n=s.substring(st,p);try{return n.indexOf('.')>=0||n.indexOf('e')>=0||n.indexOf('E')>=0?Double.valueOf(n):Long.valueOf(n);}catch(Exception e){throw err("bad number");}} private void lit(String x){if(!s.startsWith(x,p))throw err("bad literal");p+=x.length();}private void ws(){while(p<s.length()&&Character.isWhitespace(s.charAt(p)))p++;}private boolean peek(char c){return p<s.length()&&s.charAt(p)==c;}private void need(char c){ws();if(!peek(c))throw err("expected "+c);p++;}private IllegalArgumentException err(String m){return new IllegalArgumentException(m+" at "+p);}}
}
