package ngl.relay.core;
import java.io.*; import java.net.*; import java.nio.charset.StandardCharsets;
public abstract class HttpNode implements Node {
  protected final String nodeId,apiKey,provider,baseUrl,model;
  protected HttpNode(String id,String key,String provider,String base,String model){this.nodeId=id;this.apiKey=key;this.provider=provider;this.baseUrl=base;this.model=model;}
  public String nodeId(){return nodeId;} public String provider(){return provider;} public String model(){return model;}
  public boolean isConfigured(){return apiKey!=null&&!apiKey.trim().isEmpty()&&baseUrl!=null&&!baseUrl.trim().isEmpty()&&model!=null&&!model.trim().isEmpty();}
  protected void configureAuth(HttpURLConnection c){c.setRequestProperty("Authorization","Bearer "+apiKey);} protected void configureHeaders(HttpURLConnection c){}
  protected abstract String requestBody(String prompt); protected abstract String extractContent(String body) throws NodeException;
  protected static String esc(String s){StringBuilder b=new StringBuilder("\""); for(char c:s.toCharArray()){switch(c){case '\\':b.append("\\\\");break;case '"':b.append("\\\"");break;case '\n':b.append("\\n");break;case '\r':b.append("\\r");break;case '\t':b.append("\\t");break;default: if(c<32)b.append(String.format("\\u%04x",(int)c));else b.append(c);}}return b.append('"').toString();}
  private static String readAll(InputStream in)throws IOException{if(in==null)return "";BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));StringBuilder b=new StringBuilder();String x;while((x=r.readLine())!=null)b.append(x).append('\n');return b.toString();}
  public NodeResult execute(String prompt,int timeout) throws NodeException {HttpURLConnection c=null;long start=System.currentTimeMillis();try{c=(HttpURLConnection)new URL(endpoint()).openConnection();c.setRequestMethod("POST");c.setConnectTimeout(timeout);c.setReadTimeout(timeout);c.setRequestProperty("Content-Type","application/json");c.setRequestProperty("Accept","application/json");configureAuth(c);configureHeaders(c);c.setDoOutput(true);try(OutputStream out=c.getOutputStream()){out.write(requestBody(prompt).getBytes(StandardCharsets.UTF_8));}int status=c.getResponseCode();String raw=readAll(status>=200&&status<300?c.getInputStream():c.getErrorStream());if(status<200||status>=300)throw new NodeException(provider+" HTTP "+status,status,raw);String content=extractContent(raw);if(content==null||content.trim().isEmpty())throw new NodeException(provider+" empty completion",status,raw);return new NodeResult(content,model,status,System.currentTimeMillis()-start);}catch(NodeException e){throw e;}catch(Exception e){throw new NodeException(provider+" transport failure: "+e,-1,"");}finally{if(c!=null)c.disconnect();}}
  protected static String jsonStringField(String json,String key){String pat="\""+key+"\"";int p=json.indexOf(pat);if(p<0)return null;p=json.indexOf(':',p+pat.length());if(p<0)return null;p++;while(p<json.length()&&Character.isWhitespace(json.charAt(p)))p++;if(p>=json.length()||json.charAt(p)!='"')return null;p++;StringBuilder b=new StringBuilder();boolean esc=false;for(;p<json.length();p++){char c=json.charAt(p);if(esc){switch(c){case'n':b.append('\n');break;case'r':b.append('\r');break;case't':b.append('\t');break;default:b.append(c);}esc=false;}else if(c=='\\')esc=true;else if(c=='"')break;else b.append(c);}return b.toString();}
}
