package ngl.relay.core;
public final class MethodologyEngine {
 public static final int STAGE_1_INDEPENDENT=1,STAGE_2_CROSS=2,STAGE_3_ITERATIVE=3,STAGE_4_DELIBERATION=4,STAGE_5_SYNTHESIS=5;
 public static final String S1_PROMPT="You are an independent cognition node. Respond to the ORIGINAL INPUT below. You have NOT seen any other analysis. Think carefully, state your reasoning, and clearly flag your uncertainties.\n\nORIGINAL INPUT:\n";
 public static final String S2_TASK="You are one cognition node in a relay. Other nodes have independently analyzed the same original input (their preserved outputs follow). Your job: critique, compare, corroborate, and CONTRADICT. Say plainly where you disagree with the other nodes and why. Do not soften disagreement. If you agree, say what specifically convinces you. End with the single most important unresolved question.";
 public static final String S3_TASK="You are one cognition node in a relay, now seeing the accumulated record: the original input, your own and other nodes' independent analyses, and the cross-exposure critiques. Interrogate the material further: refine, dig into the unresolved questions, and add anything genuinely new. Do not repeat what is already established without adding to it.";
 public static final String S4_TASK="You are the deliberation layer. You are given the ENTIRE accumulated record. Produce a structured deliberation with these sections, filled honestly (omit none, label empty sections explicitly):\nAGREEMENTS — where nodes converge and on what exact basis\nDISAGREEMENTS — substantive conflicts, node vs node, quoted where useful\nCONTRADICTIONS — direct logical/factual conflicts in the material\nUNCERTAINTIES — what remains genuinely uncertain\nMISSING INFORMATION — what evidence would resolve the open questions\nCOMPETING INTERPRETATIONS — genuinely different readings of the same material\nUNRESOLVED QUESTIONS — the open list, ranked by importance\nDo NOT manufacture consensus. Disagreement is information.";
 public static final String S5_TASK="You are the synthesis layer. From the ENTIRE accumulated record — including all disagreements and the deliberation — produce a useful, actionable final synthesis for the human who owns this case. Be concrete. Where the nodes genuinely disagree, present the disagreement and the practical consequences of each side rather than forcing a resolution. This synthesis is a derived artefact to help a human decide — it is NOT verified truth.";
 private MethodologyEngine(){}
}
